### ISSUE TITLE
Why I cannot use transforms.ifft2?

### ISSUE THREAD

**Issue by creator2020A** [facebookresearch/fastMRI#115]
I have these imports:

import h5py
import numpy as np
import matplotlib.pyplot as plt
import torch
from fastmri.data import transforms

from these the following command works fine
sl2=transfroms.to_tensor(slice_kspace)

But when I write
image=transforms.ifft2(sl2)

I get the following error:
AttributeError: module 'fast.data.transforms has no attribute ifft2

Where can I find ifft2 , definitely this not from numpy. Where do you get this module transforms?

**Comment by mmuckley** [comment]
Hello @creator2020A, sorry for the belated reply.

`ifft2c` is name-spaced under `fastmri`, like [here](https://github.com/facebookresearch/fastMRI/blob/1146a066dc4e1440bba629dc40f3edc761509894/fastmri/models/varnet.py#L188).

Is there any documentation where you saw this usage? This needs to be updated.

**Comment by creator2020A** [comment]
Yes, I saw but not on your companies website. Some other site. Thank you for your reply.
