### ISSUE TITLE
Fat Suppressed images

### ISSUE THREAD

**Issue by samyak0210** [facebookresearch/fastMRI#12]
How can I know which images are PD and PDFS from the h5 file in single coil

**Comment by veritas9872** [comment]
There's a variable in the attributes of each HDF5 file.

**Comment by anuroopsriram** [comment]
`
with h5py.File(tgt_file) as data:
      acquisition_type = data.attrs['acquisition']  # should be 'CORPD_FBK' or 'CORPDFS_FBK'
`
