### ISSUE TITLE
Training with Dicom or converting dicom to kspace

### ISSUE THREAD

**Issue by sukeshfrt** [facebookresearch/fastMRI#120]
1) I would like to try training fastMRI with dicom dataset, Is that possible?
2) Is there a way to convert dicom to kspace, is there any code in repo, or any other way?
please guide me, Thanks in Advance

**Comment by mmuckley** [comment]
Hello @sukeshfrt.

To my knowledge this is an open research problem. I don't know of anyone that has used the DICOM data. There are a lot of issues with it, including quantization, the magnitude operation, and interpolation, that make it impossible to calculate the original k-space. So you'll need to come up with a new research method if you want to do this.
