### ISSUE TITLE
Regularization Weights

### ISSUE THREAD

**Issue by samyak0210** [facebookresearch/fastMRI#13]
Can someone explain to me what are the acceleration and regularization weights in the metric table of single coil baseline? I want to retrieve my own table for these metrics.

**Comment by anuroopsriram** [comment]
Which single coil baseline? We presented two baseline models in the paper and we have two tables corresponding to them (tables 4 & 6).

**Comment by samyak0210** [comment]
Table 4

**Comment by anuroopsriram** [comment]
The accelerations and regularization weights are the first and second columns in the table, respectively. You can run `models/cs/run_bart_val.py` to get these results.

To set 4x acceleration factor, set `--accelerations 4 --center-fractions 0.08` and for 8x acceleration factor, set `--accelerations 8 --center-fractions 0.04`. To set the regularization weight, use the `--reg-wt` argument.
