### ISSUE TITLE
Training the VarNet model fails if the Trainer object has more than 1 logger object

### ISSUE THREAD

**Issue by ant0nsc** [facebookresearch/fastMRI#133]
I'm trying to train the `VarNetModule` with a PL Trainer that has two logger objects. This fails in [line 116 of `mri_module`](https://github.com/facebookresearch/fastMRI/blob/5176a62b079520aea8d72db4e2c3536199467aba/fastmri/pl_modules/mri_module.py#L115), where the code is accessing the `SummaryWriter` object in the logger.
```
self.logger.experiment.add_image(f"{key}/target", target, global_step=self.global_step)
```
It would be great to have that code a bit more flexible: For example, if the loggers are a list, search for one that is a `TensorBoardLoger`, and only on those call `add_image`. Happy to PR that.

**Comment by mmuckley** [comment]
Closed by PR #134.
