### ISSUE TITLE
Implementation of the  cascade module in the code is different from the paper. 

### ISSUE THREAD

**Issue by akemisetti** [facebookresearch/fastMRI#138]
The  [VarNetBlock ](https://github.com/facebookresearch/fastMRI/blob/43718c3f1d0be52228c65d3e2b27ac492122c0d5/fastmri/models/varnet.py#L243) is in line with the paper "End-to-End Variational Networks for Accelerated MRI Reconstruction" except for one part. 

The equation for the cascade says 
![image](https://user-images.githubusercontent.com/4714062/118383863-a4e3cd00-b5b6-11eb-83b1-1ebc695634fc.png)

But in the code 
`return current_kspace - soft_dc - model_term`

model_term is subtracted in the code but in the paper, the refinement module is added to the current_kspace in every iteration.  
It looks like I am missing something in the implementation.  Can you please explain.

**Comment by mmuckley** [comment]
Hello @akemisetti, practically, this shouldn't cause any difference. It just flips the sign of the weights. I checked and this is how the code was originally committed.

Since the published model weights that we have expect the current behavior, we won't be changing this.

**Comment by mmuckley** [comment]
Closing for now.
