### ISSUE TITLE
is mkl-random 1.0.1 necessary & error in requrement.txt

### ISSUE THREAD

**Issue by yjump** [facebookresearch/fastMRI#15]
Hi all,
     When I try pip install -r requirement.txt, there are some errors happening.
     What I know is that pytorch 0.4.0 cannot be intalled by pip directly. But, mkl-random is incompatible with intel-numpy according to this requirement.txt. there is no mkl-random used in this code, I would like to ask is mkl-random 1.0.1 necessary in this repo?

ERROR: mkl-random 1.0.1 has requirement intel-numpy<1.15,>=1.14, but you'll have intel-numpy 1.15.1 which is incompatible.

**Comment by anuroopsriram** [comment]
Hi: If I remember correctly, the mkl packages are only needed for installing the BART toolkit, so unless you are using the classical compressed sensing methods (code in `models/cs`), you should not need those packages.
