### ISSUE TITLE
the reconstruction result of jupyter notebook

### ISSUE THREAD

**Issue by NayeeC** [facebookresearch/fastMRI#164]
I have tried the `fastMRI_tutorial.ipynb`, using the multicoil_knee data. However, the results of the full sample and the subsample look the same. Why does this happen?
![8}9(A~YZ40J}1ZKURVTAH10](https://user-images.githubusercontent.com/45288194/130565392-bcfcd4a8-9856-41a0-bddb-34c719ab0f4d.png)
![)Q{JI0OJ5L0 A5EE$PH524G](https://user-images.githubusercontent.com/45288194/130565466-784c51dd-866d-4509-b06b-8b7dc44d560a.png)

**Comment by mmuckley** [comment]
Hello @NayeeC, I can't reproduce this. Have you tried restarting the notebook from the beginning to make sure that you've wiped any other variables you have? Also, I'm not sure that images looks like `file1000167.h5`.

**Comment by NayeeC** [comment]
Hello @mmuckley, I use the `file1000082_v2.h5`, and I think everything is ok. The dataset I donwload is `knee_singlecoil_test_v2`, and there are no file named `file1000167.h5`.

**Comment by mmuckley** [comment]
@NayeeC, in that case the result makes sense. The test data has already been subsampled. If you want to have fully-sampled data, you need to use the training or validation splits.

**Comment by NayeeC** [comment]
@mmuckley, that's it!! Thank you.

**Comment by mmuckley** [comment]
Closing for now as this seems resolved.
