### ISSUE TITLE
Add fastMRI+ data compatibility to SliceDataset

### ISSUE THREAD

**Issue by mmuckley** [facebookresearch/fastMRI#178]
We would like to incorporate functionality for using the [fastMRI+ dataset](https://arxiv.org/abs/2109.03812) in this GitHub repository. In short, this should:

- Be able to download the `csv` files from the [fastMRI+ GitHub](https://github.com/microsoft/fastmri-plus/).
  - Include a git hash-based versioning system
 - Parse the `csv` and link it to samples in `SliceDataset`. It might be nice if parsing were done by the standard library so we didn't have to add a dependency, but `pandas` could be acceptable with some justification.

All of this should be feasible by subclassing and extending `SliceDataset` in [mri_data.py](https://github.com/facebookresearch/fastMRI/blob/main/fastmri/data/mri_data.py). I'm posting the issue for anyone that might want to pick up the project.

**Comment by mmuckley** [comment]
CC @hansenms

**Comment by mattnsoleil** [comment]
Hello,

In VarNet,  The dataset just loads images with the PIL library and does not convert them into necessary types like list or Tensor in 
SliceDataset. Consequently, this gives  an error  like  TypeError: batch must contain tensors, numbers, dicts or lists; found object. Is it a solution  or an update for this problem?

**Comment by mmuckley** [comment]
@mattnsoleil that is not related to implementing fastMRI+. Please open as separate issue.
