### ISSUE TITLE
Submission not working.

### ISSUE THREAD

**Issue by veritas9872** [facebookresearch/fastMRI#21]
Hello. I recently tried to add some extra submissions on EvalAI.
However, they are still "Running" after several days.
Moreover, the fact that they are running prevents me from making extra submissions.
I have raised this issue on the EvalAI forum but I think that raising it here would be faster.
Could anyone please tell me what has happened with my submission?

**Comment by anuroopsriram** [comment]
Hi, we have stopped using EvalAI a few months ago. You can submit on https://fastmri.org directly after creating an account.

**Comment by veritas9872** [comment]
Thank you. I will submit on the website.
