### ISSUE TITLE
minor problem on `fastMRI_tutorial.ipynb`

### ISSUE THREAD

**Issue by YuyangXueEd** [facebookresearch/fastMRI#232]
Hey guys! Thanks for this great dataset and toolbox. I'm just starting out in this field and trying out this awesome dataset. Just a little problem when I run `fastMRI_tutorial.ipynb`, I found that:

```
masked_kspace, mask = T.apply_mask(slice_kspace2, mask_func) 
```

makes an error. The old API return only two parameters but now is three. I hope someone can change it.

```
# add `_`, `num_low_frequencies`, or something else
masked_kspace, mask, _ = T.apply_mask(slice_kspace2, mask_func) 
```

I hope this can help newcomers who just begin to learn MRI Recon. Thanks 😃

**Comment by mmuckley** [comment]
Closed by PR #233.
