### ISSUE TITLE
Providing smaller sample data

### ISSUE THREAD

**Issue by MichaelGofron** [facebookresearch/fastMRI#25]
Hello I've been struggling to get enough space on my laptop for all the training examples. Have we considered create a single data example download available so that one can follow the example provided without downloading the full dataset. 

On a related note, I'm curious what's the standard procedure for working with this big of a dataset? Do you use a dev server with a lot of TB of storage on something like AWS or hook up an external hard-drive with sufficient storage? 

Thanks!

**Comment by veritas9872** [comment]
@MichaelGofron Personally, I would recommend using just the single-coil knee data if you are planning to use just a laptop. 

I have developed a [script](https://github.com/veritas9872/fastMRI-kspace/blob/master/conversion_script.py) that can compress complex-valued data to half its original size. Please feel free to use it.

As for myself, I have found that an external hard drive is good enough for most use cases. The knee data set is less than 700GB when compressed. The brain data set can also be reduced in half.

A 4TB HDD storage device is not terribly expensive and can hold the entire data set if compressed.

**Comment by Bala93** [comment]
@MichaelGofron You can consider downloading only the validation data for your initial set of experiments.
