### ISSUE TITLE
Allow the data objects (module and dataset) to filter on contrast

### ISSUE THREAD

**Issue by zaccharieramzi** [facebookresearch/fastMRI#256]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

It would be nice to be able to do the following:

```python
data_module = FastMriDataModule(
    ...,
	test_contrasts='CORPD_FBK',
	val_contrasts='CORPD_FBK',
	train_contrasts=['CORPD_FBK', 'CORPDFS_FBK'],
)
```

This would enable:
- generalization tests
- finer evaluation

I want this to perform finer evaluation anyway, so I can do a PR if interested.

**Comment by mmuckley** [comment]
Hello @zaccharieramzi, this is a pretty good idea, but I think we would probably prefer to have something a little more generic. Would you consider a lambda function that could be applied to the `examples` attribute of `SliceDataset`? You could use the lambda to filter based on any data stored in the `examples` tuples.

**Comment by zaccharieramzi** [comment]
Agreed. Let me work on this.

**Comment by zaccharieramzi** [comment]
Maybe the only issue is then that you don't have argparse support, but I guess it can always be added by the end user.
