### ISSUE TITLE
torch.eig is deprecated for a long time and is being removed

### ISSUE THREAD

**Issue by kit1980** [facebookresearch/fastMRI#266]
PyTorch's torch.eig was deprecated since version 1.9 and is being removed by https://github.com/pytorch/pytorch/pull/70982. Please use the torch.linalg.eig function instead if you want your code to continue to work with the latest PyTorch.

Affected file:
https://github.com/facebookresearch/fastMRI/blob/37ffc89309c941f00ac873f5dd9b6f537411cb10/banding_removal/fastmri/data/transforms.py#L507

**Comment by Lezcano** [comment]
If the covariance is Hermitian (as it shoñuld be) you should use `linalg.eigh`.

**Comment by mmuckley** [comment]
@adefazio Could you submit a PR to fix this deprecation?

**Comment by adefazio** [comment]
The complex_whiten function appears to not be used so I'm going to remove it rather that fix it, does that make sense?
