### ISSUE TITLE
Unable to submit results to brain track

### ISSUE THREAD

**Issue by Can-Zhao** [facebookresearch/fastMRI#291]
I was not able to submit results to brain track. But knee track is allowed.
Is this behavior expected?

**Comment by mmuckley** [comment]
Hello @Can-Zhao, this is expected. We recently released the test set for the brain data and are no longer operating the leaderboard. You can download the fully-sampled data and calculate the metrics yourself if you need them for a paper.

https://github.com/facebookresearch/fastMRI/discussions/284
