### ISSUE TITLE
h5py file open error

### ISSUE THREAD

**Issue by Bala93** [facebookresearch/fastMRI#3]
**OSError: Unable to open file (file read failed).** 

In the dataloader __init__ ( I am opening the h5 file and finding the no of slices) and forming a tuple. 

In the dataloader __iterator__ ( I am opening the h5 file again with file name and slice no). 

I am getting the above mentioned error randomly. What might be the issue ?

**Comment by jzbontar** [comment]
1. Are you using the [provided data loader](https://github.com/facebookresearch/fastMRI/blob/bab0759b3cb2e0adc2ff84ada53687ae735bf21d/data/mri_data.py) or did you write your own?

2. Do the same errors happen when you read the files sequentially, in a for loop? For example, using the following script:

```python
import h5py
import pathlib

for fname in pathlib.Path('PATH_TO_DATA/multicoil_train/').iterdir():
    x = h5py.File(fname, 'r')['kspace'][()]
    print(fname, x.sum(), x.shape)
```

**Comment by Bala93** [comment]
It was a mistake. The file got corrupted while transferring. Now the issue is not coming. I am following the same procedure as in your code. Changing an index into file, slice information is clever. This approach has opened up a lot of options for us. Thank you.
