### ISSUE TITLE
Test reconstructions using varnet.py

### ISSUE THREAD

**Issue by sbhadra2020** [facebookresearch/fastMRI#32]
In the script `varnet.py`, the `test_step` function as defined under the class `VariationalNetworkModel(MRIModel)` seems to be copied from the `train_unet.py` function and I had to edit it to be consistent with the `train_step` and `validation_step` functions in `varnet.py`. The `else` branch under `def run(args)` is also missing `model.hparams=args`. These created some issues for me while testing the reconstructions and I wanted to verify if these are indeed errors or if I'm missing something. Thanks!

**Comment by tullie** [comment]
These are bugs, thanks for finding them. Do you want to send out a PR with the corrections?

**Comment by sbhadra2020** [comment]
Sure, no problem. I'll send a pull request.
