### ISSUE TITLE
Corrupted file for brain DICOM data

### ISSUE THREAD

**Issue by mmuckley** [facebookresearch/fastMRI#330]
As documented in Discussion #287, the `tar.gz` file for the brain DICOM data seems to be corrupted. I have downloaded a couple of times, observing an SHA256 hash of `68e19447b428ab723d62bcd09a2b859a06eac52f4d5751d5b66570de0f7064db` vs. the expected `04da798eda6f49986f79c8b8758d80d12d943d29776070befdf54cb5682359de`. I'm currently trying to reach out to NYU to see if we can recompress the data and reupload an uncorrupted file.

**Comment by zhijian-yang** [comment]
Hello! I have met the same problem. Can I ask if there is any way to solve this problem?

**Comment by mmuckley** [comment]
Hello @zhijian-yang, the version of the DICOM data has been reverted to the 2018 version and this Issue should now be resolved!
