### ISSUE TITLE
'ExperimentWriter' object has no attribute 'add_image'

### ISSUE THREAD

**Issue by King-pand** [facebookresearch/fastMRI#333]
Please:
version：fastrmi0.3.0 pytorch_lightning:1.9.4
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/fastmri/pl_modules/mri_module.py", line 152, in log_image
    self.logger.experiment.add_image(name, image, global_step=self.global_step)
AttributeError: 'ExperimentWriter' object has no attribute 'add_image'
- [1] Check for duplicate issues.
- [2] Provide a simple example for how to reproduce the bug.
- [3] If applicable, include full error messages/tracebacks.

**Comment by mmuckley** [comment]
Hello @King-pand, does the issue resolve if you install tensorboard to your environment?

**Comment by King-pand** [comment]
Thank you very much for your answer, I solved this problem by downloading Tensorboard.

**Comment by King-pand** [comment]
Nǐ hǎo, xiǎng wèn yīxià duō xiànquān xīgài cèshì jí shùjù wéi shén me méiyǒu zhēnshí bèijǐng shùjù? Wǒ zhǐ zài cèshì jī shùjù zhòng kàn dàole chóngjiàn shùjù.







Translate by voice








46&nbsp;/&nbsp;5,000







Translation results

Translation result
Thank you very much. I have solved the above problem by the method you mentioned. 
I would like to ask why there is no real background data in the multi-coil knee test set data? I only see the reconstructed data in the test machine data.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/fastMRI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 晚上9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/fastMRI] 'ExperimentWriter' object has no attribute 'add_image' (Issue #333)





 
Hello @King-pand, does the issue resolve if you install tensorboard to your environment?
