### ISSUE TITLE
About acquisitions

### ISSUE THREAD

**Issue by xiaoiker** [facebookresearch/fastMRI#34]
Hey,

As in discription, there are two kinds of acquisitions in the single coil data.  Are they in pairs? Like one PD data has a corresponding PDFS data? If so, How can I get them by pairs? Thanks a lot.

**Comment by tullie** [comment]
Hi @xiaoiker,

Unfortunately, although there is patients with both PD and PDFS in the dataset, there's no way of identifying the pairs.

**Comment by xiaoiker** [comment]
Okay, Thanks anyway.
