### ISSUE TITLE
No such directory created : experiments/unet

### ISSUE THREAD

**Issue by singlepoint** [facebookresearch/fastMRI#38]
Hello there,

I could only see experiments/lightning_logs directory after running the unet singlecoil baseline for 50 epochs. Where should I find the checkpoints for testing? Another important points is that in lightning_logs directory I can see 4 more directories which are version_0, version_1, version_2 and version_3. Only version_3/checkpoints contain a model checkpoint but I can't find the experiments/unet directory which is mentioned in README. Any ideas please?

**Comment by mmuckley** [comment]
Hello, the implementation of PyTorch Lightning is constantly in flux (but is hopefully stabilizing now), including how it configures checkpooint directories. I've updated the README for the U-Net model.

Basically each time you run an experiment, PyTorch Lightning by default will create a new version in the `lightning_logs` directory and increment the version count. You can change how these directories are named via callbacks - see [here](https://pytorch-lightning.readthedocs.io/en/stable/callbacks.html) for more details.

**Comment by mmuckley** [comment]
Closing for now - feel free to reopen if you'd like to discuss further.
