### ISSUE TITLE
Issue running pytest

### ISSUE THREAD

**Issue by adithyaOvGu** [facebookresearch/fastMRI#41]

**Comment by adithyaOvGu** [comment]
I am a first time user of Bart and the FastMRI repo. I followed the instructions and installed BART successfully and when I run "pytest" what are the input arguments to be passed? 

I get the follwing erros:
"with open(sys.argv[1], 'r') as fd:
IndexError: list index out of range"
"ERROR bart/tests/pyBART_run_test.py - NameError: name 'line' is not defined"  

I kindly request you to let me know where i am going wrong. Thanks in advance.

**Comment by mmuckley** [comment]
Hello, this is not one of our tests. You might have installed the BART toolbox in the same folder that you have the fastMRI repository. I'd recommend moving the BART toolbox outside the repository and then rerunning `pytest`.

If you still want to run this test and are having issues, I'd recommend asking on the BART GitHub.

https://github.com/mrirecon/bart

**Comment by adithyaOvGu** [comment]
@mmuckley Thank you for the quick response. That's exactly what I was doing, installed the BART toolbox in the same folder that has the fastMRI repository because "run_bart_test.py" and "run_bart_val.py" were calling module "bart". When I installed bart outside the repo dir, pytest works. Thank you very much.
