### ISSUE TITLE
Is there any information about generating other 2D undersampling mask?

### ISSUE THREAD

**Issue by yjump** [facebookresearch/fastMRI#42]
Hi, thanks a lot for your contribution.
I recognize that there is only 1D cartersian mask in this repo. I would like to ask where can I find some information about generating other 2D mask such as radial?

**Comment by mmuckley** [comment]
Hello, we don't have any utilities at the moment for other sampling masks, but you can implement any sampling pattern you like by subclassing [MaskFunc](https://github.com/facebookresearch/fastMRI/blob/932d57aa637bb80f745c1bc5c0c34e3a6b2b5601/common/subsample.py#L21-L44).

**Comment by mmuckley** [comment]
Closing for now - feel free to reopen if you want to discuss further.
