### ISSUE TITLE
Unable to access .h5 files

### ISSUE THREAD

**Issue by adithyaOvGu** [facebookresearch/fastMRI#43]
I am trying to train the program using the commands mentioned in fastMRI/models/unet/, where I have passed the necessary arguments. I am faced with the following error; 

" File "/Users/user./PycharmProjects/fastMRI/fastMRI/data/mri_data.py", line 49, in __init__
    data = h5py.File(fname, 'r')
  File "/Users/user/PycharmProjects/fastMRI/venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__ swmr=swmr)
  File "/Users/user/PycharmProjects/fastMRI/venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid

fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
" 
After some online searches, I found that this error occurs only if the .h5 files are corrupted during download or that the files in specified path are not of .h5 type. But in my case, the files are fine because I can access them when I try from a new script. 

I kindly request you to provide your insight into what could be the issue. Thanks in advance.

**Comment by mmuckley** [comment]
I did some searching on this error and it seems it can be caused by a variety of sources. I don't think it is specific to the fastMRI package though - you may want to check on more h5py-specific channels.

**Comment by adithyaOvGu** [comment]
@mmuckley Thank you for the quick response. I will check the h5py repo to find some solutions and I will close this issue.

**Comment by gabrielziegler3** [comment]
@adithyaOvGu Have you found any solutions for the h5 problem?
