### ISSUE TITLE
Ground truth for precomputed sensitivity map

### ISSUE THREAD

**Issue by Bala93** [facebookresearch/fastMRI#45]
For one of my experiment, I need to run varnet with precomputed sensitivity data. But when I try doing that loss is not getting reduced, instead, it's oscillating. I think the problem is due to the difference between rss of multi channels and rss of multi channels obtained by expansion through sensitivity maps. I also made couple of zero-filled submissions for both these scenarios, rss of multi channels was giving better metrics compared to latter one. 

In the varnet paper, it was mentioned that experiments have also been conducted with precomputed sensitivity maps. Is there any trick involved in making the code work for precomputed sensitivity maps? Am I missing something ? 

PS: I use bart tool to obtain sensitivity map

**Comment by mmuckley** [comment]
I think the team did use BART, but I think that for some versions of BART the sensitivity maps could have large phase errors, so we had to use the MATLAB estimator. Do you think this could apply to your case?

**Comment by mmuckley** [comment]
Closing this after a week of inactivity, but feel free to reopen if you'd like to discuss further.
