### ISSUE TITLE
Regarding dowloading the data

### ISSUE THREAD

**Issue by Bala93** [facebookresearch/fastMRI#49]
Can I download the uncompressed data ? I am thinking of using aws, since the data is in S3 bucket can I directly get the uncompressed data to my storage ? 

Otherwise I have to download the zip file extract it, which consumes twice the memory. 

Any suggestions on how to go about this ?

**Comment by mmuckley** [comment]
We don't actually manage the data - you might want to email fastmri@med.nyu.edu. I don't think they will alter the storage format, though.

**Comment by Bala93** [comment]
Sure. Thank you.
