### ISSUE TITLE
No attribute of `acceleration` in h5 file of singlecoil_val

### ISSUE THREAD

**Issue by jurader** [facebookresearch/fastMRI#5]
Although evaluate.py checks the attributes of `acceleration` and `acquisition`,  all h5 files in singlecoil_val has no attribute of `acceleration`. 

On the other hand, all h5 files in singlecoil_val has attribute of `acquisition`.

**Comment by jzbontar** [comment]
I think that's expected. Examples in *_train and *_val are fully-sampled and don't have the `acceleration` parameter, while examples in *_test have undersampled k-space and the `acceleration` parameter specifies the degree of undersampling (either 4 or 8). All examples have the `acquisition` parameter, which specifies whether the image is fat-suppressed or not.

I'd have to ask @anuroopsriram, but it looks to me like the evaluate.py script is not intended to be run by participants of the fastMRI challenge. Rather it is included to show how submissions are evaluated on the server.

**Comment by anuroopsriram** [comment]
Hey: You can run the `evaluate.py` script on validation data without the `--acceleration` argument. I have removed that argument from the code to remove the confusion. 
For the tables in the paper, I used 4x or 8x sampling on the full validation data to get better estimates of the metrics. So, when you run `run_model.py`, use `--accelerations 4 --center-fractions 0.08` for 4x or `--accelerations 8 --center-fractions 0.04` for 8x. Then run `evaluate.py` on each of the outputs.

**Comment by jurader** [comment]
Thank you for your response. 
I figure out that, even after the update, we can use evaluate.py for assessing the performance of model in validation set. 
For reproducing the tables, I can use run_model.py, with several options. I will try it. Thank you for your suggestion.  


     ----- Original Message -----
