### ISSUE TITLE
UNET model appears to be incorrect

### ISSUE THREAD

**Issue by veritas9872** [facebookresearch/fastMRI#6]
Hello. I have noticed that the unet model in the code is slightly different from the model used in the arxiv paper (p.17).

The model in the paper has only 1 convolution at the bottom block, whereas the model in the code has two of them. 

Although I have found that having this extra convolution increases performance significantly, it may be worth fixing either the code or the paper.

**Comment by anuroopsriram** [comment]
Thanks for pointing this out. The results in the paper use two convolutions, similar to what is in the code. We will fix the paper.
