### ISSUE TITLE
What exactly is being called in train_demo:: Possible multi-echo, multi contrast reconstruction

### ISSUE THREAD

**Issue by gregbruss** [facebookresearch/fastMRI#69]
Hi, I'm wondering if someone can clarify exactly what is being called in the train_unet_demo.py. The overall structure is

Main Training Routine:
  1. INIT lightning model
  2. INIT trainer 
  3. Start training (or test), followed by build and training + model configuration arguments.

But where does the data transform happen? How is it related to the train_unet.py script where the DataTransform class is defined? 

I am attempting to get the U-Net working on "simulated" multi-echo data, first by seeing if I can reconstruct the same image but as a stack of 4 (duplicating the same image and concatenating along some dimension) . Essentially, I want to feed in 4 corrupted images, and get out 4 corrected images. This is just to sanity check that the network is able to handle the dimensions before switching to true multi-echo data, where it could reconstruct multiple echoes at the same time, but where each echo leads to an image of the same underlying anatomy but with a different contrast.

**Comment by mmuckley** [comment]
Hello, `UnetModule` is a PyTorch Lightning module. For a brief overview of how PyTorch Lightning works, you can check out their [documentation](https://pytorch-lightning.readthedocs.io/en/latest/new-project.html).

More specifically here, the `UnetModule` inherits from `MriModule`, which you can find [here](https://github.com/facebookresearch/fastMRI/blob/master/fastmri/mri_module.py). The `MriModule` defines the data loaders and applies the transforms. Within `MriModule` there is a placeholder function `train_data_transform()`, which is defined in `UnetModule`. It can be confusing, but most projects that use the fastMRI data will reuse the same data interface code in `MriModule`, and using this subclass structure helps us maintain data loading aspects in one place in the code base. The specific place where the transforms are applied is in the `__getitem__` function of `SliceDataset` [here](https://github.com/facebookresearch/fastMRI/blob/30ab1d4bbe5bea70e8970c4806138c2731009fbf/fastmri/data/mri_data.py#L213).

For your specific use case I think you can mostly work on modifying `DataTransform` to generate your images at different echoes. After this [line](https://github.com/facebookresearch/fastMRI/blob/30ab1d4bbe5bea70e8970c4806138c2731009fbf/experimental/unet/unet_module.py#L259) I think you should have multi-coil complex data, if I'm reading correctly.

Let me know if this helps with your question.

**Comment by mmuckley** [comment]
Closing for now. Feel free to reopen if you'd like to discuss further.

**Comment by gregbruss** [comment]
Hi, yes, moving ahead with this project. Thanks for your previous comment, that clarified a lot for me.

As mentioned above, I'm currently trying to augment the baseline U-Net to work with multiple inputs and outputs, using as a start the multi-coil brain data.

I mentioned the idea behind this in an earlier [forum post](https://discuss.fastmri.org/t/unrelated-to-challenge-possibility-of-fast-multi-echo-reconstruction/182). Jointly reconstructing a set of separate MR contrasts (stacked along the channel dimension) could allow us to undersample very aggressively, as the network can make use of the shared, latent anatomical representation across them. In the paper you mentioned, from MGH, reasonable image quality at R=16-fold acceleration for a set of 3 contrasts (T1w, T2w, T2-FLAIR) at sub-1mm isotropic resolution was demonstrated, with a total acquisition time of <3 minutes.


To handle multi-channel input/output, I've loaded in the multi-coil brain data. After RSS, I stack the same [image](https://github.com/gregbruss/fastMRI/blob/master/experimental/unet/unet_module.py#L275) 4 times along the channel dimension. I do the same for [target](https://github.com/gregbruss/fastMRI/blob/master/experimental/unet/unet_module.py#L288).

Initially this causes a problem in the [forward](https://github.com/facebookresearch/fastMRI/blob/master/experimental/unet/unet_module.py#L88) pass of the network, as torch.stack adds a dimension and will cause a weight-matrix to data-size mismatch during the forward conv in the downsampling path:

`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [128, 4, 3, 3],but got 5-dimensional input of size [1, 1, 4, 384, 384] instead`

My solution for this was to remove the unsqueeze(1) operation from the [forward call](https://github.com/gregbruss/fastMRI/blob/master/experimental/unet/unet_module.py#L91) in UnetModule as we already have that additional dimension from stack. 

The training step appears to work, however I'm getting an assertion error at the end of the validation epoch end function:

`File "../../fastmri/mri_module.py", line 207, in validation_epoch_end
    assert val_logs[0]["output"].ndim == 3`

It seems that the validation step returns a [dictionary](https://github.com/facebookresearch/fastMRI/blob/master/experimental/unet/unet_module.py#L111) after every step which is saved to val_logs, and at the end of the validation epoch, these dictionaries are concatenated into a list. But what are the 3 outputs here? And is this expected? Any advice on how best to approach making the U-Net multi-channel, before loading in actual multi-contrast data, is appreciated.

**Comment by mmuckley** [comment]
Hello, in this case the 3 dimensions are x, y, and z. If you're reconstructing multiple contrasts, you may want to alter this module to properly visualize for your application.

PyTorch Lightning has pretty good documentation on how LightningModules work and how to get things going.

https://pytorch-lightning.readthedocs.io/en/latest/
