### ISSUE TITLE
training blocked when using bn layer

### ISSUE THREAD

**Issue by tfzhou** [facebookresearch/fastMRI#78]
Hi, Thanks for the great project.

I am recently tuning the code. However, I found that the training is blocked at the validation of the first epoch when changing instancenorm layers to bachnorm layers. The same thing happens when I use a SSIM loss instead the L1 loss. Have you met the same problem before? and why do this happens from your opinion?

**Comment by mmuckley** [comment]
Hello, could you specify which model you're training? Are you using the U-Net? And are you using the new version of the code (with imports from `fastmri`) or the old version? We've deprecated all the old code and will probably remove it after the challenge.

**Comment by tfzhou** [comment]
@mmuckley Thanks. I am using the U-Net and it should be the old version. I will try the new version to see if this is the problem.
