### ISSUE TITLE
isADirectoryError

### ISSUE THREAD

**Issue by LiqunZeng** [facebookresearch/fastMRI#83]
Hi, 
When I was trying to run the model on test data, it shows the isADirectoryError:

~/fastMRI-master$ **python models/unet/train_unet.py --mode test --challenge singlecoil --data-path DATA --exp unet --out-dir reconstructions --checkpoint /home/fastMRI-master/experiments/lightning_logs/version_12/checkpoints/**

...
...
    return _open_file(name_or_buffer, mode)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/home/fastMRI-master/experiments/lightning_logs/version_12/checkpoints/'

**Comment by mmuckley** [comment]
The argument to `--checkpoint` should be to a checkpoint file, not a directory.

**Comment by LiqunZeng** [comment]
> The argument to `--checkpoint` should be to a checkpoint file, not a directory.

Thank you!!!
