### ISSUE TITLE
Bug in EvalAI Leaderboard

### ISSUE THREAD

**Issue by veritas9872** [facebookresearch/fastMRI#9]
Hello. I recently found a slight bug in the Leaderboard for the fastMRI webpage.

In the photos below, if you look at the detailed view for the PSNR in a submission, the SSIM values are shown instead.

I have checked the EvalAI page and the results there appear to be accurate.

I believe that this is a problem with the webpage. 

I hope that this helps with the challenge.

![singlecoil](https://user-images.githubusercontent.com/33523965/56728487-d8641c80-678d-11e9-897c-81c089db04f9.png)

-----------------------------------------------------------------------------------

![multicoil](https://user-images.githubusercontent.com/33523965/56728498-def29400-678d-11e9-9aef-d751bb61f87c.png)

**Comment by anuroopsriram** [comment]
Thanks for pointing this out. We will fix this soon.
