### ISSUE TITLE
fastwri_dirs.yaml  file

### ISSUE THREAD

**Issue by jiangwenjie123** [facebookresearch/fastMRI#98]
Hello, I have a problem here, where can I download this file fastwri_dirs.yaml, thank you so much！

**Comment by mmuckley** [comment]
Hello @jiangwenjie123, we don't provide this file. Its use is optional. If you want to use it, as it states [here](https://github.com/facebookresearch/fastMRI/blob/b9c07e90e1333b3417bef28fcc9137141746cce1/fastmri/data/mri_data.py#L89-L93), it creates a template file for you that you can fill in with the paths to the fastMRI data on your system.

**Comment by PhilChina** [comment]
> Hello, I have a problem here, where can I download this file fastwri_dirs.yaml, thank you so much！

Hello, can you download the dataset  " brain_multicoil_train (1228.8 GB)"  or "brain_fastMRI_DICOM (39.6 GB)" ?  It's too large and I need too many days to download, so if you have baiduyunpan, can you share it by baiduyunpan?  Thanks.

**Comment by mmuckley** [comment]
Hello @PhilChina, these issues are only for the code repository. For questions about the data itself, please contact fastmri@med.nyu.edu.
